version: "3.8"

networks:
  default:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 169.254.48.64/29          
          
services:
  python-docker-ipam-plugin:
    hostname: python-docker-ipam-plugin
    domainname: docker.internal
    restart: unless-stopped
    command: /bin/bash -c 'pipenv install --deploy && pipenv install --dev && while true; do pipenv run dev-server; sleep 0.5; done'
    networks:
      default:
        ipv4_address: 169.254.48.66
    build:
      context: .
    volumes:
      - .:/work
      - data:/data:rw
      - /var/run/docker/plugins:/var/run/docker/plugins
    ulimits:
      nproc: 65535
      nofile:
        soft: 1024000
        hard: 1024000

volumes:
  data:
    name: pyipam_dev_data
